### PR TITLE
Config to undo when esc is pressed (Issue # 41)

### PR DESCRIPTION
**Pull request by kazupooot**

### CODE REVIEW

**Comment by hakib** [comment]
Hey man, just wanted to say i did not forget about you and i'll try to take the time and do this. 

From a quick look it seems like the solution can be a bit more generic. Maybe add the ability to set which keys are active so that you could also cancel arrow buttons and shift key etc...

**Comment by hakib** [comment]
Hey @kazupooot, In v0.3.0 you can set the ESC key code globally using a configuration provider. By settings the ESC code to non existing code you can essentially cancel it.

**Comment by kazupooot** [comment]
I think that solves my problem. Thanks!

**Comment by hakib** [comment]
Great!

**Pull request closed without merging**
